### ISSUE TITLE
Can't enter email/password for parent login on mobile

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#1]
Text just doesn't appear in the text box for email address or password when trying to sign in on mobile (IOS 9.3.2, Safari)

**Comment by ThePlushEater** [comment]
Fixed. The below css was blocking the iPhone text input.
-moz-user-select: all;
-ms-user-select: all;
-webkit-user-select: all;
user-select: all;

So, I remove all user-select css.
