### ISSUE TITLE
Address look up issues

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#16]
I need to place a tree at "888 grayson new hope road". The address lookup on the FoodParent map can't find it, but google maps does no problem. any idea why?

also, when you click the address at the top of the screen, can you make it not delete the existing address?

**Comment by durkie** [comment]
Also it'd be better to show the full address in the address bar if possible. Any address I type in now gets the street number removed

**Comment by durkie** [comment]
It looks like trees that I add to the database also have this address stored -- we really need the street number in order for the address to be useful.

**Comment by ThePlushEater** [comment]
The address changed because whenever I get lat and lng from Google API, I pass those location data to the reversegeocoding api to get the address. To fix this issue, I will swap the current reverse geocoding api into the Google Reverse Geo API. I will apply this and commit.
