### ISSUE TITLE
check EXIF data for rotation?

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#20]
this might be for version 2.1, but images that are rotated don't show up correctly oriented after upload

**Comment by ThePlushEater** [comment]
Ah yes, that's the issue that I checked when the picture is taken from cell phone. The code should be simple. I will check later.

**Comment by ThePlushEater** [comment]
Upload progress...

**Comment by durkie** [comment]
I'm making a lot of issues, but I consider this one of the more important ones. I'm sitting on a lot of photos that I don't want to upload yet because I'd have to manually rotate all of them.
