### ISSUE TITLE
don't auto-update address look up / address look up should auto-zoom

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#22]
the address bar isn't very useful when really zoomed out, and while we'll want an address for trees, finding an address for random places on the map is not going to be a common use case.

i'd prefer the address lookup bar to function more like google maps: you type something in, it takes you to that location, zoomed-in.

**Comment by ThePlushEater** [comment]
I actually fix that part, automatically zoom in when the address is typed. Also, if you put a just number, like 124, it will find a tree and zoom in to the tree location. I haven't commit lately since I am fixing bunch of bugs.. but you will see tomorrow.
