### ISSUE TITLE
can you get rid of delete tree functionality?

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#27]
we don't really want anyone deleting trees. if they want to get rid of a tree they can mark it dead or hidden

**Comment by ThePlushEater** [comment]
I can totally remove this feature, or only open to admin account, which can be you or someone.

**Comment by ThePlushEater** [comment]
I think if I give this option for only admin (you or Katherine), it won't be a problem. I just want to keep this option open just in case some wrong trees are added accidentally.

**Comment by durkie** [comment]
okay, that's fine.

i just pulled the master branch and am getting it built. i'll be able to tell you about it late tonight hopefully
