### ISSUE TITLE
show in season trees

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#28]
an sql query like this will work for now:

``` sql
select distinct tree.food from note join tree on note.tree = tree.id where note.rate>3 and datediff(note.date,CURRENT_DATE) < 30
```

**Comment by ThePlushEater** [comment]
what about season fruits for filter? Do you have idea how to decide what kinds of fruits we are going to show?

**Comment by durkie** [comment]
i'm not sure i understand -- can't you use that sql query to decide what fruits to show?

**Comment by ThePlushEater** [comment]
Ah yes, you are right. I misunderstood the query statement. It should work for both food filter and which trees to show on the map.
