### ISSUE TITLE
user name should take up less space on mobile navbar

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#32]
right now when I'm logged in, my username "craig@concrete-jungle" takes up almost half of the navbar on my phone. how about a 👤  icon or something?

we probably don't really need a logo in the navbar either, unless it were a CJ logo -- i think it's kind of confusing from a branding standpoint

**Comment by ThePlushEater** [comment]
I agree both points. For CJ logo, do you want me to use the logo on the concrete jungle site?

**Comment by ThePlushEater** [comment]
https://www.concrete-jungle.org/wp-content/themes/green-apples/images/logo.png

This is the logo that I found in the CJ site. Do you have another version without a background? or a logo more like a square shape? You can send me any kind of logo related images, then I will work based on from them.

**Comment by ThePlushEater** [comment]
My bad. The logo doesn't have any background. It's already transparent. I can work from it.

**Comment by ThePlushEater** [comment]
But I do still want some kind of icon that I can use as favicon and etc. Do you have a bigger resolution of favicon that CJ site is currently using?

**Comment by durkie** [comment]
nah, can't find it -- you can google image search for a fig leaf, or just use the one we're already using?

**Comment by ThePlushEater** [comment]
I need to work on the logo later more.
