### ISSUE TITLE
Remove flags section from the filter list for users that aren't logged in

### ISSUE THREAD

**Issue by ThePlushEater** [PublicDesignWorkshop/FoodParent2.0#4]
I assume users who aren't logged in doesn't need to see the flag filter. What about users who log in as a parent? Do they need to see the flag filter, if so, why? what is the difference usages between two user groups?

**Comment by durkie** [comment]
For now I don't have much of an opinion on this. Do for parents whatever is easiest. They probably don't need to see flags though.

I guess one thing that we haven't discussed if it tree parents could be assigned a private tree. Ideally they could, but I don't know how feasible it is.

**Comment by ThePlushEater** [comment]
I will leave this issue open so that we can decide later. For now, I took out the flag filter for both guests and parents. Only managers can see the filter flag. It means that parents and guests can **ONLY** see **VERIFIED** trees on the map.

**Comment by ThePlushEater** [comment]
Closed.
