### ISSUE TITLE
Too many login/admin checks

### ISSUE THREAD

**Issue by ThePlushEater** [PublicDesignWorkshop/FoodParent2.0#6]
For now, I execute login/admin check for each view component, The problem is that these php files are executed too many times for no apparent reason. I need to reconstruct the flow of user type checking so that it checks only one time, and pass the login type information via "React context".

**Comment by durkie** [comment]
How do you store login type in the front end and keep it secure? Are you just proposing using a cookie?

**Comment by ThePlushEater** [comment]
I do store login information in a cookie, but still I need to check at least one time every time user do something. But if you see the network log, it checks too many times because I call login check from multiple view components. To fix this, I need to call one time from the view in a top hierarchy and pass information to children views.

**Comment by ThePlushEater** [comment]
Fixed.
